USE wedding_stephens_page;

CREATE TABLE IF NOT EXISTS mailing_addresses (
    mailing_group INT PRIMARY KEY,
    address_1 VARCHAR(255) DEFAULT NULL,
    address_2 VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    zip VARCHAR(20) DEFAULT NULL,
    country VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
